name: Ubuntu

on:
  push:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'
    - '.gitattributes'
    - '.gitignore'
    - 'LICENSE'
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false  # if a particular matrix build fails, don't skip the rest
      matrix:
        arch: ['x64', 'x86']

    steps:
    - uses: actions/checkout@v2

    - name: Install x64 SDL and deps
      if: ${{ matrix.arch == 'x64' }}
      run: |
        sudo apt-get update --fix-missing
        sudo apt-get install alien libsdl2-dev libjpeg-dev libwebp-dev libtiff5-dev libsdl2-image-dev libmikmod-dev libfishsound1-dev libsmpeg-dev liboggz2-dev libflac-dev libfluidsynth-dev libsdl2-mixer-dev libfreetype6-dev libsdl2-ttf-dev libsdl2-net-dev -y

    - name: Install x86 SDL and deps
      if: ${{ matrix.arch == 'x86' }}
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update --fix-missing
        sudo apt-get install gcc-multilib g++-multilib
        sudo apt-get install alien libsdl2-dev:i386 libjpeg-dev:i386 libwebp-dev:i386 libtiff5-dev:i386 libsdl2-image-dev:i386 libmikmod-dev:i386 libfishsound1-dev:i386 libsmpeg-dev:i386 liboggz2-dev:i386 libflac-dev:i386 libfluidsynth-dev:i386 libsdl2-mixer-dev:i386 libfreetype6-dev:i386 libsdl2-ttf-dev:i386 libsdl2-net-dev:i386 -y

    - name: Build sources, tests and make installer
      run: sudo python3 build.py --make installer --use-alien --arch ${{ matrix.arch }}
    
    - name: Install from .deb installer and test
      run: sudo apt-get install ./dist/packaging/*.deb

    - name: Run tests
      run: kcr  # CKithare currently doesn't have unittests

    - name: Upload installer
      uses: actions/upload-artifact@v2
      with:
        name: kithare-linux-installers
        path: dist/packaging/
